import {calculate,type DB} from './engine';
import {faNum,tr} from './fa';

const avg=(values:number[])=>values.length?values.reduce((a,b)=>a+b,0)/values.length:0;
export default function Analytics({db,period}:{db:DB;period:string}){
 const teams=[...new Set(db.people.map(p=>p.team))];
 const refs=new Map<string,number>();db.evidence.forEach(e=>refs.set(`${e.source}:${e.reference}`,(refs.get(`${e.source}:${e.reference}`)||0)+1));
 const duplicateCount=[...refs.values()].filter(n=>n>1).length;
 const reviewerRows=[...new Set(db.workItems.map(w=>w.roles.reviewer))].map(id=>{const items=db.workItems.filter(w=>w.roles.reviewer===id),returned=items.filter(w=>w.events.some(e=>e.eventType==='Returned'||e.eventType==='Reopened')).length;return {id,name:db.people.find(p=>p.id===id)?.name||id,count:items.length,returnRate:items.length?returned/items.length*100:0}});
 return <><div className="notice"><div><h2>کنترل انصاف، الگوی مدیریت و نشانه‌های بازی‌دادن سیستم</h2><p>تحلیل‌ها بر مبنای فرصت کاری، پیچیدگی، بازگشت، بازبین و انتساب علت انجام می‌شوند. داده‌های ویژگی حفاظت‌شده در فایل موجود نیست؛ بنابراین ممیزی جمعیتی تا اتصال منبع مجاز غیرفعال است.</p></div></div>
 <div className="stats"><section className="stat"><div>مرجع تکراری</div><strong>{faNum(duplicateCount)}</strong><small>کنترل ثبت دوباره شواهد</small></section><section className="stat"><div>کار روتین</div><strong>{faNum(db.workItems.filter(w=>w.complexity.band==='Routine').length)}</strong><small>پایش انتخاب کار آسان</small></section><section className="stat"><div>انتساب به مدیریت</div><strong>{faNum(db.workItems.filter(w=>w.attributionCause==='Management-created overload'||w.attributionCause==='Unrealistic deadline at assignment').length)}</strong><small>از قابلیت اتکای مجری کسر نمی‌شود</small></section><section className="stat"><div>نمونه اعتبارسنجی</div><strong>{faNum(db.sampling.length)}</strong><small>ریسک‌محور و تصادفی</small></section></div>
 <section className="panel"><div className="panel-title"><h2>سلامت و برابری فرصت تیم‌ها</h2><span className="badge">بدون توزیع اجباری</span></div><div className="table-wrap"><table><thead><tr><th>تیم</th><th>افراد</th><th>میانگین امتیاز</th><th>پیچیدگی متوسط</th><th>نرخ پذیرش شاهد</th><th>توقف تأیید</th></tr></thead><tbody>{teams.map(team=>{const people=db.people.filter(p=>p.team===team),ids=new Set(people.map(p=>p.id)),items=db.workItems.filter(w=>w.team===team),ev=db.evidence.filter(e=>e.period===period&&ids.has(e.personId)),scores=people.map(p=>calculate(db,p,period).score).filter((n):n is number=>n!==null);return <tr key={team}><td><strong>{tr(team)}</strong></td><td>{faNum(people.length)}</td><td>{faNum(avg(scores))}</td><td>{faNum(avg(items.map(w=>w.complexity.workUnits)))} واحد</td><td>{faNum(ev.length?ev.filter(e=>e.status==='Verified').length/ev.length*100:0)}٪</td><td>{faNum(people.filter(p=>calculate(db,p,period).hold).length)}</td></tr>})}</tbody></table></div></section>
 <section className="panel"><div className="panel-title"><h2>سازگاری بازبین‌ها</h2><small>نرخ بازگشت غیرعادی، نمونه اعتبارسنجی مستقل ایجاد می‌کند</small></div><div className="table-wrap"><table><thead><tr><th>بازبین</th><th>اقلام بررسی‌شده</th><th>نرخ بازگشت/بازگشایی</th><th>علامت کنترل</th></tr></thead><tbody>{reviewerRows.map(r=><tr key={r.id}><td>{r.name}<small>{r.id}</small></td><td>{faNum(r.count)}</td><td>{faNum(r.returnRate)}٪</td><td><span className="badge">{r.returnRate>35?'نیازمند اعتبارسنجی':'در محدوده'}</span></td></tr>)}</tbody></table></div></section></>
}
