import {Activity,Database,GitBranch,ShieldCheck} from 'lucide-react';
import type {DB,Role} from './engine';
import {faDate,faNum,faSource,faPeriod,tr} from './fa';

const roleNames:Record<string,string>={requester:'درخواست‌دهنده',planner:'برنامه‌ریز',assigner:'واگذارکننده',decision_owner:'مالک تصمیم',executor:'مجری',contributor:'مشارکت‌کننده',reviewer:'بازبین'};
const eventNames:Record<string,string>={Assigned:'واگذار شد',Started:'شروع شد',Submitted:'ارسال شد',Accepted:'پذیرفته شد',Returned:'برگشت خورد',Reopened:'بازگشایی شد',Blocked:'مسدود شد',Unblocked:'رفع انسداد شد','Artifact linked':'سند متصل شد','Sample selected':'برای نمونه انتخاب شد','Sample reviewed':'نمونه بازبینی شد','Result approved':'نتیجه تأیید شد'};
const periodStates:Record<string,string>={Open:'باز',Calculating:'در حال محاسبه',Locked:'قفل‌شده',Published:'منتشرشده'};
const cadence:Record<string,string>={Monthly:'ماهانه',Quarterly:'فصلی',Semiannual:'شش‌ماهه'};

export default function Controls({db,period,role,onUpdate}:{db:DB;period:string;role:Role;onUpdate:(db:DB,action:string)=>void}){
 const events=db.workItems.flatMap(w=>w.events.map(e=>({...e,workType:w.workType})));
 const exceptions=db.workItems.filter(w=>w.exception);
 return <>
  <div className="stats"><section className="stat"><div>رویدادهای استانداردشده<Activity size={16}/></div><strong>{faNum(events.length)}</strong><small>جریان فقط‌افزودنی UWES</small></section><section className="stat"><div>رابط‌های منبع<Database size={16}/></div><strong>{faNum(db.connectors.length)}</strong><small>همه در حالت پایگاه نمایشی</small></section><section className="stat"><div>نمونه‌های کنترلی<ShieldCheck size={16}/></div><strong>{faNum(db.sampling.length)}</strong><small>تصادفی، ریسک‌محور و اعتبارسنجی</small></section><section className="stat"><div>نقش‌های مسئولیت<GitBranch size={16}/></div><strong>{faNum(7)}</strong><small>برای هر کار به‌صورت مستقل</small></section></div>
  <section className="panel"><div className="panel-title"><div><h2>رابط‌های منبع و کاربرد داده</h2><small>همه ورودی‌ها پیش از امتیازدهی به قرارداد رویداد استاندارد تبدیل می‌شوند</small></div><span className="badge">حالت نمایشی</span></div><div className="table-wrap"><table><thead><tr><th>منبع</th><th>کاربرد</th><th>رکورد</th><th>آخرین همگام‌سازی</th><th>سلامت</th></tr></thead><tbody>{db.connectors.map(c=><tr key={c.id}><td><strong>{c.name}</strong><small>{faSource(c.id)}</small></td><td>{c.purpose}</td><td>{faNum(c.records)}</td><td>{faDate(c.lastSync)}</td><td><span className="badge green">سالم · ساختگی</span></td></tr>)}</tbody></table></div></section>
  <section className="panel"><div className="panel-title"><div><h2>چرخه‌های ارزیابی</h2><small>تغییر داده فقط در دوره باز مجاز است و گذار چرخه در اختیار حاکمیت است</small></div></div><div className="table-wrap"><table><thead><tr><th>دوره</th><th>تناوب</th><th>وضعیت</th><th>انتشار</th><th>عملیات</th></tr></thead><tbody>{db.periods.map(p=>{const next=p.state==='Open'?'Calculating':p.state==='Calculating'?'Locked':p.state==='Locked'?'Published':null;return <tr key={p.id}><td>{faPeriod(p.id)}</td><td>{cadence[p.cadence]}</td><td><span className="badge">{periodStates[p.state]}</span></td><td>{p.publishedAt?faDate(p.publishedAt):'—'}</td><td><button disabled={role!=='Governance'||!next} onClick={()=>next&&onUpdate({...db,periods:db.periods.map(row=>row.id===p.id?{...row,state:next,publishedAt:next==='Published'?new Date().toISOString():row.publishedAt}:row)},`دوره ${faPeriod(p.id)} به «${periodStates[next]}» منتقل شد`)}>{next?`انتقال به ${periodStates[next]}`:'پایان‌یافته'}</button></td></tr>})}</tbody></table></div></section>
  <div className="project-grid"><section className="panel"><div className="panel-title"><h2>صف نمونه‌برداری خودکار</h2><span className="badge">{faNum(db.sampling.filter(s=>s.status==='Queued').length)} باز</span></div><div className="table-wrap"><table><thead><tr><th>کار</th><th>روش و دلیل</th><th>وضعیت</th></tr></thead><tbody>{db.sampling.map(s=><tr key={s.id}><td>{s.workItemId}<small>{s.id}</small></td><td>{s.method==='Random'?'تصادفی':'ریسک‌محور'}<small>{s.reasons.join('، ')}</small></td><td><span className="badge">{s.status==='Reviewed'?'بازبینی‌شده':'در صف'}</span></td></tr>)}</tbody></table></div></section><section className="panel"><div className="panel-title"><h2>استثنا و انتساب علت</h2><span className="badge">{faNum(exceptions.length)} مورد</span></div><div className="table-wrap"><table><thead><tr><th>کار</th><th>استثنا</th><th>شدت</th><th>انتساب</th></tr></thead><tbody>{exceptions.map(w=><tr key={w.id}><td>{tr(w.workType)}<small>{w.id}</small></td><td>{tr(w.exception!.type)}</td><td><span className="badge">{tr(w.exception!.severity)}</span></td><td>{tr(w.attributionCause||'—')}</td></tr>)}</tbody></table></div></section></div>
  <section className="panel"><div className="panel-title"><div><h2>جریان رویداد استانداردشده</h2><small>رویدادهای منبع به کار، عامل و نقش پاسخ‌گو متصل‌اند</small></div><span className="badge">{faPeriod(period)}</span></div><div className="table-wrap"><table><thead><tr><th>زمان</th><th>رویداد</th><th>کار</th><th>عامل</th><th>نقش مسئولیت</th><th>رده</th></tr></thead><tbody>{events.slice().sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt)).slice(0,80).map(e=><tr key={e.id}><td>{faDate(e.occurredAt)}</td><td><strong>{eventNames[e.eventType]||tr(e.eventType)}</strong><small>{e.id}</small></td><td>{tr(e.workType)}<small>{e.workItemId}</small></td><td>{db.people.find(p=>p.id===e.actorId)?.name||e.actorId}</td><td>{roleNames[e.responsibilityRole]}</td><td>{e.category==='work'?'کار':e.category==='control'?'کنترل':'حاکمیت'}</td></tr>)}</tbody></table></div></section>
 </>
}
