const fa: Record<string,string> = {
  Overview:'نمای کلی','My impact':'اثرگذاری من',People:'افراد',Projects:'پروژه‌ها','People analytics':'تحلیل نیروی انسانی',Evidence:'شواهد','Quality review':'بازبینی کیفیت','Data & controls':'داده و کنترل‌ها',Calibration:'هم‌ترازی',Appeals:'اعتراض‌ها','Performance pay':'پرداخت عملکرد','Model & policy':'مدل و سیاست','Audit trail':'ردپای ممیزی',
  Employee:'کارمند',Manager:'مدیر',Reviewer:'بازبین',Calibrator:'هم‌ترازکننده',Governance:'ناظر حاکمیت',Payroll:'کارشناس حقوق','Model admin':'مدیر مدل',
  Transactional:'تراکنشی',Project:'پروژه‌ای',Knowledge:'دانشی',Coordination:'هماهنگی',Control:'کنترلی',Management:'مدیریتی',
  Contribution:'مشارکت',Quality:'کیفیت',Reliability:'قابلیت اتکا',Stewardship:'پاسداری',Collective:'مشارکت جمعی',
  High:'بالا',Moderate:'متوسط',Low:'پایین','Not ratable':'غیرقابل ارزیابی',Verified:'تأییدشده',Pending:'در انتظار',Returned:'برگشت‌خورده',Rejected:'ردشده',Draft:'پیش‌نویس',Reviewed:'بازبینی‌شده',Calibrated:'هم‌تراز‌شده',Approved:'تأیید نهایی',Open:'باز',Resolved:'حل‌شده',
  Calculating:'در حال محاسبه',Locked:'قفل‌شده',Published:'منتشرشده',Assigned:'واگذارشده',Started:'شروع‌شده',Submitted:'ارسال‌شده',Accepted:'پذیرفته‌شده',Reopened:'بازگشایی‌شده',Blocked:'مسدودشده',Unblocked:'رفع انسدادشده','Artifact linked':'سند متصل‌شده','Sample selected':'انتخاب نمونه','Sample reviewed':'بازبینی نمونه','Result approved':'نتیجه تأییدشده',
  'Below standard':'پایین‌تر از استاندارد','Partially meets':'تا حدی منطبق','Meets standard':'منطبق با استاندارد','Exceeds standard':'فراتر از استاندارد',
  Upheld:'تأیید اعتراض','Partially upheld':'تأیید جزئی',Overturned:'رد اعتراض',
  'Insufficient evidence':'شواهد ناکافی','Critical exception':'استثنای بحرانی','Open appeal':'اعتراض باز','Low confidence':'اطمینان پایین',
  Minor:'جزئی',Major:'عمده',Critical:'بحرانی',Incorrect:'نادرست',Incomplete:'ناقص','Procedural non-compliance':'عدم انطباق رویه‌ای','Missing documentation':'مدارک ناقص','Unclear / not fit for purpose':'نامشخص یا نامتناسب با هدف','Incorrect authorization':'مجوز نادرست','Missed risk':'ریسک شناسایی‌نشده','Missed deadline':'مهلت ازدست‌رفته','Duplicate or unnecessary work':'کار تکراری یا غیرضروری','Unrealistic deadline at assignment':'مهلت غیرواقعی هنگام واگذاری','Management-created overload':'بارکاری ایجادشده توسط مدیریت','External outage or unavailable dependency':'اختلال یا وابستگی بیرونی','Employee delay without blocker':'تأخیر کارمند بدون مانع',
  'Claims Operations':'عملیات خسارت','Underwriting Support':'پشتیبانی صدور بیمه','Core Platform Engineering':'مهندسی پلتفرم مرکزی','Data & Integration':'داده و یکپارچه‌سازی','Compliance & Audit':'انطباق و ممیزی','Risk Advisory':'مشاوره ریسک','Customer Service Coordination':'هماهنگی خدمات مشتری','Legal & Knowledge Advisory':'مشاوره حقوقی و دانشی',
  'Insurance Operations':'عملیات بیمه','Engineering & Delivery':'مهندسی و تحویل','Risk & Compliance':'ریسک و انطباق','Customer & Legal':'خدمات مشتری و حقوقی','Executive Leadership':'رهبری اجرایی',
  'People Management':'مدیریت افراد','Operations / Claims Processing':'عملیات و رسیدگی به خسارت','Operations / Underwriting':'عملیات صدور بیمه','Engineering / Data Platform':'مهندسی پلتفرم داده','Risk & Compliance / Audit':'ریسک و انطباق / ممیزی','Risk & Compliance / Advisory':'ریسک و انطباق / مشاوره','Legal & Advisory':'حقوقی و مشاوره',
  Executive:'مدیرعامل',Director:'مدیر ارشد واحد',Senior:'ارشد',Mid:'میانی',Junior:'مقدماتی',Lead:'راهبر',
  'Claim adjudication':'رسیدگی به خسارت','Payment processing':'پردازش پرداخت','Refund request':'درخواست بازپرداخت','Policy binding review':'بازبینی صدور بیمه‌نامه','Endorsement processing':'پردازش الحاقیه','Renewal verification':'راستی‌آزمایی تمدید','Migration cutover':'انتقال نهایی سامانه','Integration build':'پیاده‌سازی یکپارچه‌سازی','Environment hardening':'سخت‌سازی محیط','Feature implementation':'پیاده‌سازی قابلیت','Data pipeline build':'ساخت خط لوله داده','Connector integration':'یکپارچه‌سازی رابط داده','Data quality remediation':'رفع مشکل کیفیت داده','Reporting automation':'خودکارسازی گزارش‌گیری','Audit finding remediation':'رفع یافته ممیزی','Access review':'بازبینی دسترسی','Risk assessment':'ارزیابی ریسک','Control test':'آزمون کنترل','Control design':'طراحی کنترل','Vendor risk review':'بازبینی ریسک تأمین‌کننده','Escalation coordination':'هماهنگی ارجاع','Ticket routing':'مسیریابی تیکت','Vendor handoff':'تحویل به تأمین‌کننده','Advisory memo':'یادداشت مشورتی','Policy draft':'پیش‌نویس سیاست','Regulatory opinion':'نظر مقرراتی',
  'Task manager':'سامانه مدیریت کار','ERP/domain system':'سامانه ERP','CRM/case system':'سامانه CRM',HRIS:'سامانه منابع انسانی',PayrollSource:'سامانه حقوق و دستمزد',DMS:'سامانه اسناد',
  KPI:'شاخص کلیدی عملکرد (KPI)',OKR:'هدف و نتیجه کلیدی (OKR)',Resolution:'مصوبه',
  'Requirement changed after submission':'تغییر نیازمندی پس از ارسال',
};
export const tr=(value:string|undefined|null)=>value==null?'—':fa[value]||value;
export const faNum=(value:number|string,maximumFractionDigits=1)=>Number(value).toLocaleString('fa-IR',{maximumFractionDigits});
export const faDate=(value:string)=>new Date(value).toLocaleString('fa-IR',{dateStyle:'medium',timeStyle:'short'});
export const faPeriod=(period:string)=>({"2026-06":'فصل اول ۱۴۰۵',"2026-07":'فصل دوم ۱۴۰۵',"2026-08":'فصل سوم ۱۴۰۵'}[period]||period);
export const faSource=(value:string)=>value==='Payroll'?tr('PayrollSource'):tr(value);
