import {ArrowUpLeft,CheckCircle2,Clock3,Database,GitBranch,LockKeyhole,ShieldCheck,Users} from 'lucide-react';
import type * as React from 'react';
import {scopeFor,type AppContext} from './access';
import {actors,calculate,dimensions,weights,type DB} from './engine';
import {faDate,faNum,faPeriod,faSource,tr} from './fa';

type Props={db:DB;context:AppContext;page:string;period:string;navigate:(page:string)=>void};
const avg=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;
const roles:Record<string,string>={requester:'درخواست‌دهنده',planner:'برنامه‌ریز',assigner:'واگذارکننده',decision_owner:'مالک تصمیم',executor:'مجری',contributor:'مشارکت‌کننده',reviewer:'بازبین'};
export const customPages=new Set(['Home','Expectations','Contributions','Responsibilities','Evidence package','Work capture','Team outcomes','Evidence gaps','System quality','Project snapshot','Attribution','Job families','Performance profiles','Integrations','Engine ledger','Calibration facilitator','Quality samples','Governance cases','Payroll preview','Access management']);

export default function RolePages({db,context,page,period,navigate}:Props){
 const person=db.people.find(p=>p.id===actors.Employee)||db.people[0],mine=db.workItems.filter(w=>Object.values(w.roles).includes(person.id));
 const results=db.people.map(p=>({p,r:calculate(db,p,period)}));
 const scope=scopeFor(db,context),scopeIds=new Set(scope.map(p=>p.id));
 const scopedResults=context.managerId||context.id==='self'?results.filter(x=>scopeIds.has(x.p.id)):results;
 const scopedTeams=context.managerId?[...new Set(scope.map(p=>p.team))]:[...new Set(db.people.map(p=>p.team))];
 const scores=scopedResults.map(x=>x.r.score).filter((x):x is number=>x!==null);
 if(page==='Home')return <><div className="role-hero"><div><span className="eyebrow">{context.roleTitle}</span><h1>{context.label.split(' — ')[1]||context.label}</h1><p>این نما فقط داده‌ها و اقدام‌های دامنه «{context.scope}» را نشان می‌دهد.</p></div><span className="secure-pill"><LockKeyhole size={15}/>دامنه دسترسی فعال</span></div><div className="stats"><section className="stat"><div>دوره فعال<Clock3 size={16}/></div><strong>{faPeriod(period)}</strong><small>{tr(db.periods.find(p=>p.id===period)?.state)}</small></section><section className="stat"><div>اقدام‌های در انتظار<ShieldCheck size={16}/></div><strong>{faNum(db.sampling.filter(s=>s.status==='Queued').length+db.appeals.filter(a=>a.status==='Open').length)}</strong><small>نمونه و پرونده در دامنه</small></section><section className="stat"><div>پوشش داده<Database size={16}/></div><strong>{faNum(avg(scopedResults.map(x=>x.r.confidence)))}٪</strong><small>میانگین اطمینان شواهد</small></section><section className="stat"><div>میانگین نتیجه<ArrowUpLeft size={16}/></div><strong>{faNum(avg(scores))}</strong><small>بدون توزیع اجباری</small></section></div><section className="panel"><div className="panel-title"><div><h2>کارهای این زمینه</h2><small>منو بر اساس قابلیت‌های مؤثر ساخته شده است</small></div></div><div className="quick-grid">{context.nav.filter(n=>n.id!=='Home').map(n=><button key={n.id} onClick={()=>navigate(n.id)}><span><strong>{n.label}</strong><small>بازکردن نمای {context.roleTitle}</small></span><ArrowUpLeft size={17}/></button>)}</div></section></>;
 if(page==='Expectations')return <Page title="انتظارات و اهداف" text="انتظارات از الگوی کاری، سطح شغلی و فرصت‌های واقعی این دوره ساخته می‌شوند."><div className="detail-stats"><Metric value={tr(person.primary)} label="الگوی اصلی"/><Metric value={faNum(person.expected)} label="واحد مورد انتظار"/><Metric value={tr(person.level)} label="سطح شغلی"/></div><Table heads={['بُعد','وزن','تعریف موفقیت']} rows={dimensions.map((d,i)=>[tr(d),`${faNum(weights[person.primary][i])}٪`,['تحویل نتیجه پذیرفته‌شده','درستی و تناسب با هدف','تحویل در محدوده کنترل فرد','رعایت کنترل و مستندسازی','اثر بر نتیجه مشترک'][i]])}/></Page>;
 if(page==='Contributions')return <Page title="مشارکت‌ها و پیامدها" text="هر مشارکت به قلم کار، نقش مسئولیت و سند قابل راستی‌آزمایی متصل است."><Table heads={['قلم کار','نقش من','پیچیدگی','پیامد','شواهد']} rows={mine.map(w=>[tr(w.workType),Object.entries(w.roles).filter(([,id])=>id===person.id).map(([r])=>roles[r]).join('، '),`${faNum(w.complexity.workUnits)} واحد`,w.events.some(e=>e.eventType==='Accepted')?'پذیرفته‌شده':'در جریان',faNum(db.evidence.filter(e=>e.workItemId===w.id).length)])}/></Page>;
 if(page==='Responsibilities')return <Page title="نقش‌ها و سهم مسئولیت" text="مسئولیت هر قلم کار از مجری، مشارکت‌کننده، تصمیم‌گیر و بازبین جدا نگه داشته می‌شود."><Table heads={['قلم کار',...Object.values(roles)]} rows={mine.map(w=>[tr(w.workType),...Object.keys(roles).map(r=>db.people.find(p=>p.id===w.roles[r as keyof typeof w.roles])?.name||'—')])}/></Page>;
 if(page==='Evidence package')return <Page title="بسته شواهد محاسبه‌شده" text="این بسته توضیح می‌دهد هر نتیجه از کدام شاهد، رویداد و وزن به دست آمده است."><Table heads={['بُعد','امتیاز','وزن','سهم وزنی']} rows={dimensions.map((d,i)=>{const r=calculate(db,person,period),v=r.values[i]??0;return[tr(d),faNum(v),`${faNum(r.w[i])}٪`,faNum(v*r.w[i]/100)]})}/></Page>;
 if(page==='Work capture')return <Page title="ثبت رویداد کار" text="ثبت دستی مسیر کنترل‌شده‌ای برای منابعی است که هنوز رابط خودکار ندارند."><div className="notice"><div><h2>ورودی دستی به صف بازبینی می‌رود</h2><p>شناسه منبع یکتا، نقش مسئولیت، پیچیدگی و سند پشتیبان الزامی است.</p></div><button className="primary" onClick={()=>navigate('Evidence')}>رفتن به ثبت شاهد</button></div></Page>;
 if(page==='Team outcomes')return <Page title="پیامدها و اهداف تیم" text="نتیجه تیم با حجم کار خام سنجیده نمی‌شود؛ پیچیدگی، پذیرش و کیفیت مبنا هستند."><Table heads={['تیم','اقلام کار','واحد پیچیدگی','پذیرفته‌شده','استثنا']} rows={scopedTeams.map(team=>{const ws=db.workItems.filter(w=>w.team===team);return[tr(team),faNum(ws.length),faNum(ws.reduce((s,w)=>s+w.complexity.workUnits,0)),faNum(ws.filter(w=>w.events.some(e=>e.eventType==='Accepted')).length),faNum(ws.filter(w=>w.exception).length)]})}/></Page>;
 if(page==='Evidence gaps')return <Page title="پوشش و شکاف شواهد" text="شکاف‌ها پیش از قفل دوره باید رفع یا با دلیل ثبت شوند."><Table heads={['فرد','تیم','پوشش','اطمینان','اقدام']} rows={scopedResults.sort((a,b)=>a.r.confidence-b.r.confidence).map(({p,r})=>[p.name,tr(p.team),`${faNum(r.confidence)}٪`,tr(r.state),r.confidence<80?'نیازمند شاهد تکمیلی':'کافی'])}/></Page>;
 if(page==='System quality')return <Page title="کیفیت سیستم کاری" text="این نما مسئله‌های ناشی از مدیریت، ظرفیت و وابستگی را از عملکرد فرد جدا می‌کند."><Table heads={['قلم کار','علت','شدت','مسئول پاسخ‌گویی','اثر بر مجری']} rows={db.workItems.filter(w=>w.attributionCause).map(w=>[tr(w.workType),tr(w.attributionCause),tr(w.exception?.severity),w.attributionCause?.includes('Management')?'مدیر/واگذارکننده':'مالک وابستگی',w.attributionCause==='Employee delay without blocker'?'محاسبه می‌شود':'حذف از قابلیت اتکا'])}/></Page>;
 if(page==='Project snapshot')return <Page title="صف نمای پروژه" text="رهبر پروژه سهم‌ها، تحویل‌ها و انتساب علت را پیش از انتشار تأیید می‌کند."><Table heads={['قلم کار','مجری','واحد','رویداد پایانی','وضعیت انتساب']} rows={db.workItems.map(w=>[tr(w.workType),db.people.find(p=>p.id===w.roles.executor)?.name||'—',faNum(w.complexity.workUnits),tr(w.events.at(-1)?.eventType),w.attributionCause?tr(w.attributionCause):'بدون اختلاف'])}/></Page>;
 if(page==='Attribution')return <Page title="تشخیص انتساب" text="زمان و کیفیت فقط به نقشی نسبت داده می‌شود که کنترل واقعی بر علت داشته است."><Table heads={['قلم کار','سناریو','نقش پاسخ‌گو','حکم قابلیت اتکا','شاهد رویدادی']} rows={db.workItems.filter(w=>w.attributionCause).map(w=>[tr(w.workType),tr(w.attributionCause),w.attributionCause==='Employee delay without blocker'?'مجری':w.attributionCause?.includes('Management')?'واگذارکننده/مدیر':'مالک وابستگی','Employee delay without blocker'===w.attributionCause?'منظور شود':'از مجری کسر نشود',w.events.filter(e=>['Blocked','Unblocked','Assigned','Submitted'].includes(e.eventType)).map(e=>tr(e.eventType)).join(' ← ')])}/></Page>;
 if(page==='Job families')return <Page title="خانواده‌های شغلی" text="نگاشت خانواده شغلی به الگوی کار نسخه‌بندی می‌شود."><Table heads={['خانواده','افراد','الگوی غالب','سطوح']} rows={[...new Set(db.people.map(p=>p.title))].map(title=>{const ps=db.people.filter(p=>p.title===title);return[tr(title),faNum(ps.length),tr(ps[0].primary),[...new Set(ps.map(p=>tr(p.level)))].join('، ')]})}/></Page>;
 if(page==='Performance profiles')return <Page title="پروفایل‌های عملکرد" text="وزن‌ها بر اساس الگوی کار تعیین می‌شوند و مسئولیت هر قلم، نوع شاهد را تعیین می‌کند."><Table heads={['پروفایل',...dimensions.map(tr)]} rows={Object.entries(weights).map(([name,row])=>[tr(name),...row.map(v=>`${faNum(v)}٪`)])}/></Page>;
 if(page==='Integrations')return <Page title="درگاه‌های داده" text="این نسخه همه رابط‌ها را در حالت نمایشی اجرا می‌کند و قرارداد تبدیل همان قرارداد تولید است."><Table heads={['درگاه','کاربرد','رکورد','آخرین همگام‌سازی','وضعیت']} rows={db.connectors.map(c=>[c.name,c.purpose,faNum(c.records),faDate(c.lastSync),'سالم · نمایشی'])}/></Page>;
 if(page==='Engine ledger')return <Page title="بازپخش و دفترکل موتور" text="هر رویداد استاندارد را می‌توان به ترتیب زمان بازپخش و نتیجه را دوباره ساخت."><Table heads={['رویداد','نوع','قلم کار','عامل','زمان']} rows={db.workItems.flatMap(w=>w.events).sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt)).slice(0,100).map(e=>[e.id,tr(e.eventType),e.workItemId,db.people.find(p=>p.id===e.actorId)?.name||e.actorId,faDate(e.occurredAt)])}/></Page>;
 if(page==='Calibration facilitator')return <Page title="مدیریت جلسات هم‌ترازی" text="تسهیل‌گر ترتیب بررسی را بر اساس اطمینان، استثنا و اختلاف تنظیم می‌کند."><Table heads={['فرد','زمینه مقایسه','امتیاز','اطمینان','اولویت جلسه']} rows={results.sort((a,b)=>a.r.confidence-b.r.confidence).map(({p,r})=>[p.name,`${tr(p.primary)} · ${tr(p.level)}`,faNum(r.score??0),`${faNum(r.confidence)}٪`,r.hold?tr(r.hold):'عادی'])}/></Page>;
 if(page==='Quality samples')return <Page title="صف نمونه‌های کیفیت" text="انتخاب نمونه از بازبینی آن جداست؛ بازبین فقط صف تخصیص‌یافته را می‌بیند."><Table heads={['نمونه','قلم کار','روش','دلیل','وضعیت']} rows={db.sampling.map(s=>[s.id,s.workItemId,s.method==='Random'?'تصادفی':'ریسک‌محور',s.reasons.join('، '),s.status==='Reviewed'?'بازبینی‌شده':'در صف'])}/></Page>;
 if(page==='Governance cases')return <Page title="پرونده‌های تخصیص‌یافته" text="پرونده، اعتراض، شواهد مرتبط و رأی مستدل را کنار هم نگه می‌دارد."><Table heads={['پرونده','فرد','دلیل','وضعیت','رسیدگی‌کننده']} rows={db.appeals.map(a=>[a.id,db.people.find(p=>p.id===a.personId)?.name||a.personId,a.reason,tr(a.status),a.actor||'تخصیص‌نیافته'])}/></Page>;
 if(page==='Payroll preview')return <Page title="پیش‌نمایش حقوق" text="هیچ رکوردی بدون سه مرحله تأیید و نبود توقف وارد خروجی نمی‌شود."><Table heads={['فرد','شناسه','امتیاز','بازه','وضعیت خروجی']} rows={results.map(({p,r})=>[p.name,p.id,faNum(r.score??0),tr(r.band),r.exportable?'آماده ارسال':'متوقف'])}/></Page>;
 if(page==='Access management')return <Page title="کاربران و دسترسی‌ها" text="در تولید، زمینه فعال از نشست احراز‌شده و مجوز سمت سرور ساخته می‌شود."><Table heads={['زمینه','نقش','دامنه','حالت']} rows={[['شخصی','کارمند','پرونده شخصی','خواندن و ثبت'],['تیم','مدیر صف','تیم تخصیص‌یافته','مدیریت شاهد'],['کیفیت','بازبین مستقل','نمونه‌های تخصیص‌یافته','تصمیم کنترل'],['حاکمیت','بازبین اعتراض','پرونده‌های تخصیص‌یافته','رأی مستدل'],['حقوق','تأییدکننده حقوق','نتایج نهایی','خروجی محدود']]}/></Page>;
 return null;
}

function Page({title,text,children}:{title:string;text:string;children:React.ReactNode}){return <><div className="notice"><div><h2>{title}</h2><p>{text}</p></div><CheckCircle2 size={25}/></div>{children}</>}
function Metric({value,label}:{value:string;label:string}){return <div><strong>{value}</strong><small>{label}</small></div>}
function Table({heads,rows}:{heads:string[];rows:(string|number)[][]}){return <section className="panel"><div className="table-wrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="empty">موردی در این دامنه وجود ندارد.</div>}</div></section>}
